### ISSUE TITLE
Training is extremely slow on a100

### ISSUE THREAD

**Issue by mehranagh20** [reyllama/mixdl#2]
I'm training your model using one a100. So far ~1300 iterations out of 150k have been done after ~10 hours. Is this how you experienced training as well? If so, why is it so slow?

**Comment by chaerinkong** [comment]
First of all, current version does not fully support distributed training, which could be one reason why your training takes longer than you would normally expect. This will be amended as well in later updates.

**Comment by iceli1007** [comment]
It is the reason of the path length regularization in generator, you can avoid it to acquire the faster training.
