### ISSUE TITLE
Implementation of Stylegan2-ADA version

### ISSUE THREAD

**Issue by 49xxy** [reyllama/mixdl#3]
Thank you very much for your excellent work!

I see that your regularization loss is deployed on Stylegan2-ADA in your article. Can you expose this version of the code?

Looking forward to your reply!

**Comment by chaerinkong** [comment]
Sorry for late reply. I'm afraid I'm not entirely sure what you mean by *this version of the code*.
Further clarification would be appreciated :)

**Comment by 49xxy** [comment]
Thanks for your reply, have you considered deploying your regularization on [stylegan2ada](https://github.com/NVlabs/stylegan2-ada-pytorch)？

**Comment by chaerinkong** [comment]
We can use stylegan2ada augmentation by activating the argument --augment. I'll try to make my code base more clean and readable as soon as possible :)
