### ISSUE TITLE
Would you release the pretrained model?

### ISSUE THREAD

**Issue by P2i42** [reyllama/mixdl#5]
Hi, thanks for your excellant work!
Recently, I tried to train mixdl models on multiple datsets(landscapes, Amedeo_Modigliani, anime_face) following the default settings in your provided code(train_mixdl+model_cdc, batch_size=4) for about 200k iterations each. 

In landscapes_art, I found that the model just reproducing the same scene in each iteration and the generated samples are kind of lack fidelity. See the figure below(60k iterations).
<img src=https://user-images.githubusercontent.com/45916661/215650480-5f63b3f7-7ebe-43cd-a83e-11d00ba15adb.png width=60% />

The results with Amedeo_Modigliani and anime_face maintains better quality and diversity. See the figure below(149k iterations)
<img src=https://user-images.githubusercontent.com/45916661/215652502-91005542-10d1-499a-9a82-1e74cac489c4.png width=60% />

Since different dataset results in different quality of generation and the iterations needed differs too, I wonder if there are different parameter settings for different dataset? If so, would you please provide the parameter settings or release the pretrained model? Or maybe there are something I ignored in my experiment, would you provide some insights? 

Thank you so much!
Best wishes

**Comment by chaerinkong** [comment]
Hmm.. that's strange. We have done experiments in different config settings, and we obtained consistent results across different hyperparam combinations. One hack you could try would be to lower `d_kl_wt` to 0.1, and `n_mlp` to 2 (though if I remember correctly, we used the default setting for both datasets). Typically, our framework yields the best samples around 50K~120K, so we recommend making image samples every 10K. Pretrained models are unfortunately currently unavailable, but I will check if we can share them in this repo. Thanks!

**Comment by P2i42** [comment]
Thanks for your reply! I will have a try.
